function audit = audit_planar_multi_contact(model, state)
% Audit all fixed planes against the entire sampled centreline, including
% contact points. Local zero gaps alone do not imply nonpenetration.
n=model.planeNormalXZ; n=n./vecnorm(n); p=model.planePointXZ;
allGap=n'*state.pXZ-sum(n.*p,1)';
nc=n(:,model.contactPlaneIndex); pc=p(:,model.contactPlaneIndex);
gap=sum(nc.*(state.contactPointsXZ-pc),1);
tangent=sum(nc.*state.contactTangentXZ,1);
audit=struct('contactGapMm',gap,'minGapByPlaneMm',min(allGap,[],2)', ...
    'maxPenetrationMm',max([0;-allGap(:)]),'maxAbsGapMm',max(abs(gap)), ...
    'maxTangencyResidual',max(abs(tangent)), ...
    'tipMomentResidualNmm',abs(state.tipMomentResidualNmm), ...
    'minNormalForceN',min(state.normalForceN), ...
    'maxComplementarityNmm',max(abs(gap.*state.normalForceN)), ...
    'orderedContacts',all(diff(state.contactS)>1e-3));
audit.passed=audit.maxPenetrationMm<1e-3 && audit.maxAbsGapMm<1e-3 && ...
    audit.maxTangencyResidual<1e-4 && audit.tipMomentResidualNmm<1e-3 && ...
    audit.minNormalForceN>=0 && audit.orderedContacts;
end
