function [input,truth] = build_formulation_free_packet(noiseStd,seed)
%BUILD_FORMULATION_FREE_PACKET Independent free-space equilibrium with tip load.
% The measured plane is far outside the shape. No contact-number label is
% supplied; the inverse must infer zero candidates from shape/environment.
if nargin<1,noiseStd=0;end;if nargin<2,seed=901;end
[input,~]=build_formulation_multi_packet([],3);
rod=input.tube;rod.T_base=input.packet.basePose(:,:,1);
tip=[0.12;0.08;-0.06];
shape=solve_cosserat_multi_contact_map(rod,[],zeros(3,0),tip, ...
    struct('relativeTolerance',2e-8,'maxRhsEvaluations',1000000));
translation=[0.2;0;0];T=2;base=repmat(rod.T_base,1,1,T);base(1:3,4,2)=base(1:3,4,2)+translation;
sensors=input.packet.sFbgMm;u=interp1(rod.s,shape.u',sensors)';
stream=RandStream('mt19937ar','Seed',seed);
input.packet=struct('schemaVersion',2,'sFbgMm',sensors,'observedCurvatureAxes',[1 2], ...
    'curvaturePerMm',repmat(u(1:2,:),1,1,T)+noiseStd*randn(stream,2,numel(sensors),T), ...
    'curvatureStdPerMm',max(noiseStd,1e-7),'basePose',base,'timeSeconds',[0 0.02], ...
    'processReferencePeriodSeconds',0.02,'planePointMm',repmat([-1000;0;0],1,1,T), ...
    'planeNormal',repmat([1;0;0],1,1,T), ...
    'planeCovariance',repmat(diag([0.05^2*ones(1,3),0.001^2*ones(1,3)]),1,1,1,T), ...
    'frictionMu',zeros(1,T));
truth=struct('p',cat(3,shape.p,shape.p+translation),'u',repmat(shape.u,1,1,T), ...
    'basePose',base,'contactS',zeros(0,T),'contactForces',zeros(3,0,T), ...
    'tipForce',repmat(tip,1,T),'totalForce',repmat(tip,1,T),'seed',seed, ...
    'scope','Independent nested-shooting free-space rod with terminal load and a distant observed plane; no body contact.');
end
