function [input, truth] = build_multi_contact_truth(kind, seed)
%BUILD_MULTI_CONTACT_TRUTH Independent multi-contact/nonplanar stress truth.
% The estimator is intentionally given only the first plane observation. The
% second reaction is generated by a separate Cosserat balance solve, so any
% degradation measures model mismatch rather than a truth leak into scoring.
if nargin < 1 || isempty(kind), kind = 'two-contact'; end
if nargin < 2 || isempty(seed), seed = 401; end
kind = char(kind);
cfg = run_rod_plane_force_sensing_experiment('sensor-config');
cfg = formulation_solver_config(cfg);
cfg.forceSensor.showProgress = false;
cfg.sensing.curvatureInterpolation = 'intrinsic-delta';
cfg.sensing.shapeSmoothing = 0;
cfg.sensing.numFbgPoints = 24;
cfg.sensing.curvatureNoiseStd = 2.5e-5;
cfg.sensing.planeOffsetNoiseStdMm = 0.05;
cfg.randomSeed = seed;
cfg.sensing.samplePeriodSeconds = 0.02;

s = unique([linspace(0,200,161),120]);
u0 = zeros(3,numel(s)); u0(2,s>=120)=1/30;
tube = make_experiment_tube(struct('exposedLengthMm',200, ...
    'rod',struct('sMm',s,'intrinsicCurvaturePerMm',u0)));
contactS = [122,168];
nt = 3; push = [0,3,6];
baseTraj = repmat(tube.T_base,1,1,nt);
p=zeros(3,numel(s),nt); u=p; R=zeros(3,3,numel(s),nt); contactPoints=zeros(3,2,nt);
previous=cell(1,nt); eq=cell(1,nt); contactForces=zeros(3,2,nt); tipForce=zeros(3,nt);
tipForce(:,1:nt)=repmat([0.35;-0.10;0.08],1,nt);
for k=1:nt
    baseTraj(3,4,k)=push(k);
    tube.T_base=baseTraj(:,:,k);
    contactForces(:,:,k)=[[0;-0.55;0.10],[0;-0.30;-0.06]];
    if strcmpi(kind,'friction-mismatch')
        contactForces(:,1,k)=[0.18;-0.55;0.10];
        contactForces(:,2,k)=[-0.12;-0.30;-0.06];
    elseif strcmpi(kind,'curved-surface')
        contactForces(:,2,k)=[0.10;-0.28;-0.16];
    end
    opts=struct('relativeTolerance',cfg.forceSensor.mechanicsRelativeTolerance, ...
        'momentToleranceNmm',cfg.forceSensor.mechanicsMomentToleranceNmm, ...
        'collisionStepMm',cfg.forceSensor.planeCollisionStepMm, ...
        'maxRhsEvaluations',max(cfg.forceSensor.mechanicsMaxRhsEvaluations,1000000));
    eq{k}=solve_cosserat_multi_contact_map(tube,contactS,contactForces(:,:,k),tipForce(:,k),opts);
    p(:,:,k)=eq{k}.p; u(:,:,k)=eq{k}.u; R(:,:,:,k)=eq{k}.R;
    contactPoints(:,:,k)=eq{k}.contactPoints;
    previous{k}=struct('p',eq{k}.p,'u',eq{k}.u,'R',eq{k}.R,'T_base',tube.T_base);
end
for k=2:nt
    previous{k}=struct('p',p(:,:,k-1),'u',u(:,:,k-1),'R',R(:,:,:,k-1), ...
        'T_base',baseTraj(:,:,k-1));
end
% Use the first contact as the observed plane. The second contact is on a
% different plane (curved-surface case) or is simply omitted (two-contact).
planeNormal=[0;-1;0];
planePoint=zeros(3,1); planePoint(:)=eq{1}.contactPoints(:,1);
secondaryPlanePoint=eq{1}.contactPoints(:,2);
secondaryPlaneNormal=planeNormal;
if strcmpi(kind,'curved-surface')
    % The second reaction is constrained by a genuinely nonparallel local
    % tangent plane. The public one-plane inverse only receives plane 1.
    secondaryPlaneNormal=[0.24;-0.91;0.34];
    secondaryPlaneNormal=secondaryPlaneNormal/norm(secondaryPlaneNormal);
end
forward=struct('betaMm',push,'internalSampleIndices',1:nt,'u',u,'p',p,'R',R, ...
    'baseTraj',baseTraj,'previousState',{previous},'frictionMu',0.25*ones(1,nt));
sim=struct('randomSeed',seed,'planePointMm',planePoint,'planeNormal',planeNormal);
sim.sensing=struct('numFbgPoints',cfg.sensing.numFbgPoints,'samplePeriodSeconds',cfg.sensing.samplePeriodSeconds, ...
    'curvatureNoiseStd',cfg.sensing.curvatureNoiseStd,'planeOffsetBiasMm',0, ...
    'planeOffsetNoiseStdMm',cfg.sensing.planeOffsetNoiseStdMm,'planeNormalNoiseStdDeg',0);
packet=simulate_sensor_packet(tube,forward,sim);
packet.planePointMm=repmat(planePoint,1,nt);
packet.planeNormal=repmat(planeNormal,1,nt);
packet.planeCovariance=repmat(diag([0.1^2*ones(1,3),0.001^2*ones(1,3)]),1,1,nt);
if strcmpi(kind,'friction-mismatch'), packet.frictionMu(:)=0.05; end
input=struct('tube',tube,'packet',packet,'config',sensor_estimator_config(cfg));
truth=struct('p',p,'u',u,'R',R,'basePose',baseTraj,'contactForces',contactForces, ...
    'contactForce',squeeze(sum(contactForces,2)),'tipForce',tipForce, ...
    'totalForce',squeeze(sum(contactForces,2))+tipForce,'contactS',contactS, ...
    'contactPoints',contactPoints,'planePoint',planePoint,'planeNormal',planeNormal, ...
    'secondaryPlanePoint',secondaryPlanePoint,'secondaryPlaneNormal',secondaryPlaneNormal, ...
    'nonplanarAngleDeg',acosd(max(-1,min(1,planeNormal'*secondaryPlaneNormal))), ...
    'kind',kind,'scope','Independent multi-contact Cosserat truth; current inverse receives one plane and one-contact state.');
end
