function cfg=calibrate_fbg_likelihood(cfg,noiseStdPerMm,modelStdPerMm)
%CALIBRATE_FBG_LIKELIHOOD Set current/history weights from declared calibration.
% Independent sensor noise and model discrepancy add in variance. A positive
% explicit model floor avoids infinite confidence for zero-noise simulation.
% Never infer these values from truth forces, estimated errors or residuals.
assert(isnumeric(noiseStdPerMm)&&isreal(noiseStdPerMm)&&isscalar(noiseStdPerMm)&& ...
    isfinite(noiseStdPerMm)&&noiseStdPerMm>=0, ...
    'rod:InvalidSensorConfig','FBG noise standard deviation must be finite and nonnegative.');
assert(isnumeric(modelStdPerMm)&&isreal(modelStdPerMm)&&isscalar(modelStdPerMm)&& ...
    isfinite(modelStdPerMm)&&modelStdPerMm>0, ...
    'rod:InvalidSensorConfig','Declare a finite positive FBG model standard deviation.');
cfg.forceSensor.measurementStd.curvature=hypot(noiseStdPerMm,modelStdPerMm);
cfg.forceSensor.historyCurvatureStdPerMm=noiseStdPerMm;
cfg.forceSensor.fbgLikelihoodCalibration=struct('noiseStdPerMm',noiseStdPerMm, ...
    'modelStdPerMm',modelStdPerMm,'effectiveStdPerMm',hypot(noiseStdPerMm,modelStdPerMm), ...
    'scope','Declared independent sensor noise plus model variance; not fitted against true forces.');
end
