function test_formulation_factor_protocol()
% Independent counting, interval exclusion and deterministic sensor sampling.
truth=struct('tipForce',zeros(3,2),'contactForces',repmat([1 2;0 0;0 0],1,1,2), ...
    'contactS',[10 10;90 90],'totalForce',repmat([3;0;0],1,2),'p',zeros(3,3,2));
estimate=struct('contactForce',repmat([1 0 2;0 0 0;0 0 0],1,1,2),'tipForce',zeros(3,2), ...
    'contactArcLength',[10 10;50 50;90 90],'activeContacts',logical([1 1;0 0;1 1]), ...
    'totalForceResultant',truth.totalForce,'quality',struct('requiresReview',[false false]), ...
    'frames',{{struct('shape',struct('p',zeros(3,3))),struct('shape',struct('p',zeros(3,3)))}}, ...
    'optimizationSeconds',1,'uncertainty',struct('computed',true,'forceStd',ones(24,1), ...
    'forceUnresolvedByData',false(24,1)));
metrics=score_formulation_window(estimate,truth);
assert(metrics.countMatches&&~metrics.candidateCountMatches&&metrics.contactForceRmseN==0&& ...
    metrics.contactArcRmseMm==0&&isequal(metrics.activeContactCount,[2 2]), ...
    'rod:ActiveSlotScoringRegression','Inactive supersets were paired with physical truth contacts.');
estimate.uncertainty.forceUnresolvedByData([1 13])=true;
coverage=score_formulation_coverage(estimate,truth,2.5e-5);
assert(coverage.eligibleComponents==16&&coverage.unresolvedComponents==2&&coverage.coveredComponents==16&& ...
    coverage.empiricalCoverage==1,'rod:CoverageExclusionRegression','Unresolved/inactive components inflated coverage.');
clean=score_formulation_coverage(estimate,truth,0);assert(~clean.computed,'Deterministic data calibrated coverage.');
estimate.activeContacts(3,2)=false;metrics=score_formulation_window(estimate,truth);
assert(~metrics.countMatches&&isnan(metrics.contactForceRmseN)&&metrics.matchedFrameCount==1, ...
    'rod:CountMismatchScoringRegression','A contact-count failure received an unconditional force score.');
packet=struct('schemaVersion',2,'curvaturePerMm',zeros(2,24,2),'curvatureStdPerMm',1e-7);
input=struct('packet',packet);a=resample_formulation_observations(input,11,2.5e-5,false);
b=resample_formulation_observations(input,11,2.5e-5,false);c=resample_formulation_observations(input,23,2.5e-5,false);
assert(isequal(a,b)&&~isequal(a,c)&&any(a.packet.curvaturePerMm(1,:,:)~=0,'all')&& ...
    any(a.packet.curvaturePerMm(2,:,:)~=0,'all')&&isequal(input.packet.curvaturePerMm,zeros(2,24,2)), ...
    'rod:NoiseRealizationRegression','Seeds/channels are not independent reproducible measurements.');
identity=struct('options',struct('sceneIds',{{'three_contact','spatial_sliding'}}, ...
    'methods',{{'full','no_camera'}},'seeds',[11 23 37],'noiseLevelsPerMm',[0 2.5e-5], ...
    'solverOptions',struct('computeCovariance',true,'constraintTolerance',1e-5)), ...
    'referenceComparisonSha256','fixture-sha', ...
    'runRecord',struct('source',struct('path',{'a.m','b.m'},'sha256',{'a-sha','b-sha'}), ...
    'dependency',struct('sourceRevision','pinned','files',struct('path',{'one.m','two.m'}, ...
    'sha256',{'one-sha','two-sha'}),'scope','required files')));
saved=jsondecode(jsonencode(identity));saved.options=orderfields(saved.options);
saved.options.solverOptions=orderfields(saved.options.solverOptions);
saved.options.seeds=saved.options.seeds(:);
assert(formulation_resume_matches(saved,identity), ...
    'rod:ResumeRoundTripRegression','A JSON checkpoint rejected unchanged sources/options.');
changed=saved;changed.runRecord.dependency.files(2).sha256='modified';
assert(~formulation_resume_matches(changed,identity),'Dependency edit bypassed resume integrity.');
changed=saved;changed.runRecord.source(1).sha256='modified';
assert(~formulation_resume_matches(changed,identity),'Source edit bypassed resume integrity.');
changed=saved;changed.options.solverOptions.constraintTolerance=1e-3;
assert(~formulation_resume_matches(changed,identity),'Solver edit bypassed resume integrity.');
fprintf('test_formulation_factor_protocol: PASS\n');
end
